### PR TITLE
New menu

### PR DESCRIPTION
**Pull request by joshmoore**
Opening for @lunson to demo under the snoopy account.

screen shot 2017-04-20 at 08 44 03

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
Lots of general impresssions:

1. I like the new top bar with the menu more than when it was at the side

2. Not sure about the Twitter/Facebook/LinkedIn/IRC bar - I find it disracting and will the content be IDR specific or be the openmicroscopy accounts.  Would a feedback/questions email button that sends us an email be better than IRC? This could be a final option on the menu bar. 
 
3. The new top bars push the rest of the page content down quite far on my screen (13" laptop) so much so that it fills the screen and its not obvious that there is anything past 'Take a look at the data' on the 'About us' page. Could the background image be cropped so that its clear there is more content on that page?

4. What is at the top of the background image changes on different pages. Might be slicker to have the same top of the image on all pages.  Where the image is cut off at the bottom might change depending on the amount of text. 

5. Because the drop downs always appear when you mouse over the 'Submissions Overview' it made me think that there was just the two 'Screens' and 'Experiments' pages and not an 'Overview' page aswell.  Maybe all 3 should appear in the drop down as 'Overview', 'Screens' and 'Experiments' and the top level text should just be 'Submissions'.  The top level could either link to the Overview if clicked on or not be a link and just allow selection from the 3 dropdown choices?

Hope this is helpful.

**Comment by joshmoore** [comment]
> Not sure about the Twitter/Facebook/LinkedIn/IRC bar ... will the content be IDR specific or be the openmicroscopy accounts. Would a feedback/questions email button that sends us an email be better than IRC? This could be a final option on the menu bar.

I'd probably limit to twitter since that's the only account we have/use. (@IDRnews and @IDRstatus for deployment issues). I like the email/feedback button.

**Comment by lunson** [comment]
> Not sure about the Twitter/Facebook/LinkedIn/IRC bar - I find it disracting and will the content be IDR specific or be the openmicroscopy accounts. Would a feedback/questions email button that sends us an email be better than IRC? This could be a final option on the menu bar.

What email do you want to use? I'll post the two twitter accounts and an email icon for the top bar in the next revision.

**Comment by lunson** [comment]
@joshmoore All of @eleanorwilliams' items have been addressed in this push. Let me know of any more changes. Thanks!

**Comment by joshmoore** [comment]
Screenshot updated.

**Comment by joshmoore** [comment]
":thumbsup:" in slack.

**Pull request merged**
