### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by joshmoore**
Similar to `deployment.html`, the new `submission.html` page will be the reference for users to begin the submission process.

@manics @eleanorwilliams

### CODE REVIEW

**Comment by manics** [comment]
A lot of whitespace changes. Intentional?

**Comment by joshmoore** [comment]
> A lot of whitespace changes. Intentional?

Yes. There are separate commits for re-indentation: https://github.com/IDR/idr-demo.openmicroscopy.org/pull/14/commits/20d518a9a33b0a66e69f7c38e9a621f148f9cf3f, https://github.com/IDR/idr-demo.openmicroscopy.org/pull/14/commits/eb536843d7eb2e7d783c7e593494bf68acb3f843

**Comment by eleanorwilliams** [comment]
I count it as 27 imaging studies not 29 - see last paragraph of index.

**Comment by joshmoore** [comment]
Ah, I found the problem. 2 rows in the dataset map weren't red that should have been. Corrected.

**Comment by eleanorwilliams** [comment]
Two typos 

1. submission.html - link to biostudies is missing the "h" in "https"
2. experiments.html - need a closing ")" after "Primary contact information (mandatory"

Also in experiments.html "analysis – the analysis pipeline to go from the image data to the results." should be indented in line with the line above.

**Comment by joshmoore** [comment]
Merging then for deployment to demo34.

**Pull request merged**
