### PR TITLE
More examples

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR provides more examples in the context of https://www.openmicroscopy.org/community/viewtopic.php?t=8153&p=17653#p17653

src in https://github.com/IDR/idr-notebooks/pull/8

### CODE REVIEW

**Comment by joshmoore** [comment]
Can you also (or rather) open against https://github.com/IDR/idr-notebooks/blob/master/notebooks/IDR_API_example_script.ipynb ?

**Comment by joshmoore** [comment]
Testing with:

```
~/opt/www.openmicroscopy.org $ docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll   -it -p 127.0.0.1:4000:4000 jekyll/jekyll
```

**Comment by aleksandra-tarkowska** [comment]
done

**Comment by joshmoore** [comment]
Merging for inclusion in demo3.1

**Pull request merged**
